export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';

export const UPDATE_FILTER = 'UPDATE_FILTER';
